#CONSTANTES

welcome = "Bienvenido a DBZ..."
levelclear = "¡Has superado el Nivel!!!"
current_level = "El nivel actual del héroe es: "
newlevel = "Has subido al nivel "
newfight = "************************NUEVO COMBATE*************************"
battlebegins = "¡Ha comenzado la batalla!"
gap = "************************************************* \n"
playerturn = "Turno de Player 1:"
enemyturn = "Turno de los enemigos:"
newlvl = "Has pasado al nivel: " 
newhealth = "Tu nueva vida es: "
newattack= "Tu nuevo ataque es: "
newenergy= "Tu nueva energy es: "